<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormController extends Controller
{
    public function index(){
        $finalForm = [
            "step_person" => [
                "id" => "step_person",
                "title" => "Datos personales",
                "show" => "d-block",
                "btnEnd" => false,
                "changeSteps" => false,
                "fields" => [
                    [
                        "field" => "task_2",
                        "type" => "text",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Nombres,",
                    ],
                    [
                        "field" => "task_3",
                        "type" => "email",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Correo electronico",
                    ],
                    [
                        "field" => "task_4",
                        "type" => "phone",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Celular",
                    ],
                ],
            ],
        ];
        $steps = [
            "step_0" => [
                "id" => "step_0",
                "title" => "¿ SOY ?",
                "show" => "d-block",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s1",
                        "type" => "checkbox",
                        "class" => "step_0",
                        "data" => 0,
                        "label" => "Hombre",
                    ],
                    [
                        "field" => "a2s1",
                        "type" => "checkbox",
                        "class" => "step_0",
                        "data" => 0,
                        "label" => "Mujer",
                    ],
                ],
            ],
            "step_1" => [
                "id" => "step_1",
                "title" => "¿Me siento aceptada por mi grupo de pares y amigos(as)?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s1",
                        "type" => "checkbox",
                        "class" => "step_1",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s1",
                        "type" => "checkbox",
                        "class" => "step_1",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_2" => [
                "id" => "step_2",
                "title" => "¿En los últimos tres meses has tenido relaciones sexuales con más de una persona? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_3" => [
                "id" => "step_3",
                "title" => "¿Al  momento de  tener relaciones sexuales, utilizas preservativo? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un Preservativo ?</p>
                <p>Más conocido como condón, es una funda  de látex (u otros materiales sintéticos) que se coloca en el pene del hombre para evitar el paso del semen hacia la mujer, evitando infecciones y embarazos. </p>
                <p>Tambien existen preservativos femenimos que funcionan de manera similar. </p>",
                "fields" => [
                    [
                        "field" => "a1s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_4" => [
                "id" => "step_4",
                "title" => "¿Actualmente utilizas algún método anticonceptivo para prevenir embarazos?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un método anticonceptivo ?</p><p>Son sustancias, objetos o procedimientos que evitan que la mujer quede embarazada. Por ejemplo; condón, las pastillas , inyecciones, parche, implante subdérmico condón (Masculino y femenino) , entre otros. </p>",
                "fields" => [
                    [
                        "field" => "a1s4",
                        "type" => "checkbox",
                        "class" => "step_4",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s4",
                        "type" => "checkbox",
                        "class" => "step_4",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_5" => [
                "id" => "step_5",
                "title" => "¿Alguna  vez has  tenido relaciones sexuales  bajo los  efectos  del alcohol  u  otra droga? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_6" => [
                "id" => "step_6",
                "title" => "¿Tus relaciones sexuales  han sido  con personas mayores  de  28 años? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_7" => [
                "id" => "step_7",
                "title" => "¿La  relación establecida  con tus cuidadores (madre o padre) te  permite hablar  de sexualidad? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_8" => [
                "id" => "step_8",
                "title" => "¿Has  recibido información relacionada  con métodos de anticoncepción a través de  amigos, padres  de familia, docentes  u otras personas? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un método anticonceptivo ?</p><p>Son sustancias, objetos o procedimientos que evitan que la mujer quede embarazada. Por ejemplo; condón, las pastillas , inyecciones, parche, implante subdérmico condón (Masculino y femenino) , entre otros. </p>",
                "fields" => [
                    [
                        "field" => "a1s8",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s8",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_9" => [
                "id" => "step_9",
                "title" => "¿Tu  mamá  fue madre  antes  de los 19 años? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_10" => [
                "id" => "step_10",
                "title" => "¿Has  tenido relaciones sexuales  bajo presión  o  en contra  de  tu voluntad? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s10",
                        "type" => "checkbox",
                        "class" => "step_10",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s10",
                        "type" => "checkbox",
                        "class" => "step_10",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_11" => [
                "id" => "step_11",
                "title" => "¿Actualmente realizas  alguna actividad deportiva, artística, cultural,  grupo juvenil  entre otras? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s11",
                        "type" => "checkbox",
                        "class" => "step_11",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s11",
                        "type" => "checkbox",
                        "class" => "step_11",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_12" => [
                "id" => "step_12",
                "title" => "¿Actualmente trabajas para generar ingresos a la familia?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s12",
                        "type" => "checkbox",
                        "class" => "step_12",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s12",
                        "type" => "checkbox",
                        "class" => "step_12",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_13" => [
                "id" => "step_13",
                "title" => "Nivel de ingresos personales",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s13",
                        "type" => "checkbox",
                        "class" => "step_13",
                        "data" => 1,
                        "label" => "Menos de un salario mínimo mensual (1 SMLV)",
                    ],
                    [
                        "field" => "a2s13",
                        "type" => "checkbox",
                        "class" => "step_13",
                        "data" => 0,
                        "label" => "Más de un salario mínimo (1 SMLV)",
                    ],
                ],
            ],
            "step_14" => [
                "id" => "step_14",
                "title" => "Edad",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s14",
                        "type" => "checkbox",
                        "class" => "step_14",
                        "data" => 1,
                        "label" => "Entre 11 y 14 años ",
                    ],
                    [
                        "field" => "a2s14",
                        "type" => "checkbox",
                        "class" => "step_14",
                        "data" => 1,
                        "label" => "Entre 15 y 19 años ",
                    ],
                ],
            ],
            "step_15" => [
                "id" => "step_15",
                "title" => "Estrato",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es estrato socioeconómico ?</p><p>Es la forma en la que un pais clasifica las condiciones de la vivienda en la que habita un grupo de personas.
                Generalemnte,  Estrato 1: Bajo-Bajo  ,    Estrato 2: Bajo , Estrato 3: Medio-Bajo ,  Estrato 4: Medio , Estrato 5: Medio-Alto ,Estrato 6: Alto.</p>
                <p>Nota: Si no lo conoces preguntale al profesional a cargo</p>",
                "fields" => [
                    [
                        "field" => "a1s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 1,
                        "label" => "0",
                    ],
                    [
                        "field" => "a2s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 1,
                        "label" => "1",
                    ],
                    [
                        "field" => "a3s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 1,
                        "label" => "2",
                    ],
                    [
                        "field" => "a4s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 1,
                        "label" => "3",
                    ],
                    [
                        "field" => "a5s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 0,
                        "label" => "4",
                    ],
                    [
                        "field" => "a6s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 0,
                        "label" => "5",
                    ],
                    [
                        "field" => "a7s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 0,
                        "label" => "6",
                    ],
                ],
            ],
            "step_16" => [
                "id" => "step_16",
                "title" => "Nivel educativo",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s16",
                        "type" => "checkbox",
                        "class" => "step_16",
                        "data" => 1,
                        "label" => "Rezagado educativo",
                    ],
                    [
                        "field" => "a2s16",
                        "type" => "checkbox",
                        "class" => "step_16",
                        "data" => 0,
                        "label" => "No rezagado educativo",
                    ],
                ],
            ],
            "step_17" => [
                "id" => "step_17",
                "title" => "Edad tu primera menstruación",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s17",
                        "type" => "checkbox",
                        "class" => "step_17",
                        "data" => 1,
                        "label" => "11 a 14 años",
                    ],
                    [
                        "field" => "a2s17",
                        "type" => "checkbox",
                        "class" => "step_17",
                        "data" => 0,
                        "label" => "15 a 19 años",
                    ],
                ],
            ],
            "step_18" => [
                "id" => "step_18",
                "title" => "¿Has tenido relaciones sexuales?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s18",
                        "type" => "checkbox",
                        "class" => "step_18",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s18",
                        "type" => "checkbox",
                        "class" => "step_18",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_19" => [
                "id" => "step_19",
                "title" => "Edad de tu primera relación sexual",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s19",
                        "type" => "checkbox",
                        "class" => "step_19",
                        "data" => 1,
                        "label" => "11 a 14 años",
                    ],
                    [
                        "field" => "a2s19",
                        "type" => "checkbox",
                        "class" => "step_19",
                        "data" => 0,
                        "label" => "15 a 19 años",
                    ],
                ],
            ],
            "step_20" => [
                "id" => "step_20",
                "title" => "Estado civil",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s19",
                        "type" => "checkbox",
                        "class" => "step_20",
                        "data" => 0,
                        "label" => "Soltera",
                    ],
                    [
                        "field" => "a2s19",
                        "type" => "checkbox",
                        "class" => "step_20",
                        "data" => 1,
                        "label" => "Unión libre/Casada/Separada",
                    ],
                ],
            ],
            "step_21" => [
                "id" => "step_21",
                "title" => "Tenencia de hijos",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s21",
                        "type" => "checkbox",
                        "class" => "step_21",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s21",
                        "type" => "checkbox",
                        "class" => "step_21",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_22" => [
                "id" => "step_22",
                "title" => "Nivel de escolaridad de mi madre",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 1,
                        "label" => "No la conocí",
                    ],
                    [
                        "field" => "a2s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 1,
                        "label" => "No tuvo ningún tipo de estudio",
                    ],
                    [
                        "field" => "a3s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 1,
                        "label" => "Sólo estudios primarios",
                    ],
                    [
                        "field" => "a4s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 0,
                        "label" => "Sólo estudios secundarios",
                    ],
                    [
                        "field" => "a5s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 0,
                        "label" => "Estudios técnicos, tecnológicos o profesionales",
                    ],
                    [
                        "field" => "a6s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 1,
                        "label" => "No sabe, No responde",
                    ],
                ],
            ],
            "step_23" => [
                "id" => "step_23",
                "title" => "Nivel de escolaridad de mi padre",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 1,
                        "label" => "No la conocí",
                    ],
                    [
                        "field" => "a2s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 1,
                        "label" => "No tuvo ningún tipo de estudio",
                    ],
                    [
                        "field" => "a3s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 1,
                        "label" => "Sólo estudios primarios",
                    ],
                    [
                        "field" => "a4s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "Sólo estudios secundarios",
                    ],
                    [
                        "field" => "a5s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "Estudios técnicos, tecnológicos o profesionales",
                    ],
                    [
                        "field" => "a6s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 1,
                        "label" => "No sabe, No responde",
                    ],
                ],
            ],
            "step_24" => [
                "id" => "step_24",
                "title" => "Beneficiario hijos dependientes de Madre cabeza de Familia",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_25" => [
                "id" => "step_25",
                "title" => "Nivel de ingresos familiares",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>Se entiende como salario mínimo el valor que por ley las empresas pagan a sus trabajadores y está en $1'117.172 pesos  (salario básico $1.000.000+ auxilio trasporte $117.172)</p>",
                "fields" => [
                    [
                        "field" => "a1s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Menos de un salario mínimo mensual (1 SMLV)",
                    ],
                    [
                        "field" => "a2s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 0,
                        "label" => "Más de un salario mínimo (1 SMLV)",
                    ],
                ],
            ],
            "step_26" => [
                "id" => "step_26",
                "title" => "Grupo étnico",
                "show" => "d-none",
                "btnEnd" => true,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 0,
                        "label" => "No aplica",
                    ],
                    [
                        "field" => "a2s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Indígenas",
                    ],
                    [
                        "field" => "a3s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Negritudes",
                    ],
                    [
                        "field" => "a4s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Rom",
                    ],
                    [
                        "field" => "a5s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Otras etnias",
                    ],
                    [
                        "field" => "a6s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Raizales",
                    ],
                    [
                        "field" => "a7s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Afrodescendiente",
                    ],
                    [
                        "field" => "a8s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "Palanquero",
                    ],
                ],
            ],
        ];

        $responses = [
            [
                "genero" => true,
                "titulo" => ["Diego","Erika"],
                "image" => "/images/riesgo_alto.png",
                "texto" => "<p>Tu vida viene desarrollándose en un contexto económico, social y cultural que te expone a un alto riesgo de un embarazo adolescente, pero ¡¡¡ANIMO!!!, Tu eres muy inteligente y  sabes  que  con  acceso  a  métodos  de  anticoncepción  y  un  proyecto  de  vida  claro,  tú DECIDES tu futuro, a continuación, te invitamos a conocer el directorio de oferta para la Prevención  de  Embarazo  Adolescente  y  a  conectarte  con  la  línea  amiga  en  Salud 3007231123  </p>
                <p>Es  importante  seguir  estas  recomendaciones  y  empoderarse  de  tu  futuro,  pues  Los padres y Las madres en la adolescencia reciben menos salario y tienen mayor tasa de desempleo, además están en alto riesgo de abandonar o postergar sus estudios, y muy pocos logran culminar una formación universitaria.  </p>
                <p>Si  eres  menor  de  14  años  recuerda  que  un  embarazo  a  tan  temprana  edad  es considerado por ley delito, por ello tienen unos derechos especiales que puedes consultar con un profesional en salud.</p>",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
            [
                "genero" => true,
                "titulo" => ["Andres","Andrea"],
                "image" => "/images/riesgo_medio.png",
                "texto" => "<p>Tu vida viene desarrollándose en un contexto económico, social y cultural que te expone a un riesgo medio de un embarazo adolescente, pero ¡¡¡ANIMO!!!Tu eres muy inteligente y  sabes  que  con  acceso  a  métodos  de  anticoncepción  y  un  proyecto  de  vida  claro,  tú DECIDES tu futuro, a continuación, te invitamos a conocer el directorio de Prevención de Embarazo Adolescente y a conectarte con la línea amiga en Salud 3007231123 </p>
                <p>Es  importante  seguir  estas  recomendaciones  y  empoderarse  de  tu  futuro,  pues  Los padres y Las madres en la adolescencia reciben menos salario y tienen mayor tasa de desempleo, además están en riesgo de abandonar o postergar sus estudios, y muy pocos logran culminar una formación universitaria.  </p>
                ",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
            [
                "genero" => true,
                "titulo" => ["Camilo","Camila"],
                "image" => "/images/riesgo_bajo.png",
                "texto" => "<p>Al estar en un riesgo bajo de un embarazo adolescente tienes una gran posibilidad de terminar una carrera universitaria, un postgrado, devengar un buen salario, sin embargo, no te confíes , siempre es necesario consultar un profesional de la salud y tener metas y sueños  claros,  te  invitamos  a  conocer  el  directorio  de  oferta  para  la  Prevención  de Embarazo Adolescente y a conectarte con la línea amiga en Salud 3007231123. </p>
                ",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
        ];

        return view('welcome', [
            'steps' => $steps,
            'finalForm' => $finalForm,
            'responses' => $responses,
        ]);
    }
}
