<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormController extends Controller
{
    public function index(){
        $finalForm = [
            "step_person" => [
                "id" => "step_person",
                "title" => "Datos personales",
                "show" => "d-block",
                "btnEnd" => false,
                "changeSteps" => false,
                "fields" => [
                    [
                        "field" => "task_2",
                        "type" => "text",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Nombres,",
                    ],
                    [
                        "field" => "task_3",
                        "type" => "email",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Correo electronico",
                    ],
                    [
                        "field" => "task_4",
                        "type" => "phone",
                        "class" => "step_1",
                        "data" => "false",
                        "label" => "Celular",
                    ],
                ],
            ],
        ];
        $steps = [
            "step_0" => [
                "id" => "step_0",
                "title" => "¿ SOY ?",
                "show" => "d-block",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s1",
                        "type" => "checkbox",
                        "class" => "step_0",
                        "data" => 0,
                        "label" => "Hombre",
                    ],
                    [
                        "field" => "a2s1",
                        "type" => "checkbox",
                        "class" => "step_0",
                        "data" => 0,
                        "label" => "Mujer",
                    ],
                ],
            ],
            "step_1" => [//¿Has tenido relaciones sexuales?
                "id" => "step_1",
                "title" => "¿Has tenido relaciones sexuales?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s1",
                        "type" => "checkbox",
                        "class" => "step_1",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s1",
                        "type" => "checkbox",
                        "class" => "step_1",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_2" => [//Edad de tu primera relación sexual
                "id" => "step_2",
                "title" => "Edad de tu primera relación sexual",
                "show" => "d-none",
                "btnEnd" => true,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 1,
                        "label" => "11 a 14 años",
                    ],
                    [
                        "field" => "a2s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 0,
                        "label" => "15 a 19 años",
                    ],
                ],
            ],
            "step_2" => [//Edad de tu primera relación sexual
                "id" => "step_2",
                "title" => "Edad de tu primera relación sexual",
                "show" => "d-none",
                "btnEnd" => true,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 1,
                        "label" => "11 a 14 años",
                    ],
                    [
                        "field" => "a2s2",
                        "type" => "checkbox",
                        "class" => "step_2",
                        "data" => 0,
                        "label" => "15 a 19 años",
                    ],
                ],
            ],
            /* "step_3" => [//¿Cuál es tu estado civil actual?
                "id" => "step_3",
                "title" => "¿ Cuál es tu estado civil actual ?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 0,
                        "label" => "Soltero(a)",
                    ],
                    [
                        "field" => "a2s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 1,
                        "label" => "Casado(a)",
                    ],
                    [
                        "field" => "a3s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 1,
                        "label" => "Separado(a)",
                    ],
                    [
                        "field" => "a4s3",
                        "type" => "checkbox",
                        "class" => "step_3",
                        "data" => 1,
                        "label" => "Unión libre",
                    ],
                ],
            ],
            "step_4" => [//¿Tienes Hijos?
                "id" => "step_4",
                "title" => "¿ Tienes Hijos ?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s4",
                        "type" => "checkbox",
                        "class" => "step_4",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s4",
                        "type" => "checkbox",
                        "class" => "step_4",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_5" => [//Total de hijos
                "id" => "step_5",
                "title" => "Total de hijos",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "0",
                    ],
                    [
                        "field" => "a2s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "1",
                    ],
                    [
                        "field" => "a3s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "2",
                    ],
                    [
                        "field" => "a4s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "3",
                    ],
                    [
                        "field" => "a5s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "4",
                    ],
                    [
                        "field" => "a6s5",
                        "type" => "checkbox",
                        "class" => "step_5",
                        "data" => 0,
                        "label" => "5",
                    ],
                ],
            ],
            "step_6" => [//Nivel de escolaridad de mi madre
                "id" => "step_6",
                "title" => "Nivel de escolaridad de mi madre",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 1,
                        "label" => "No la conocí",
                    ],
                    [
                        "field" => "a2s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 1,
                        "label" => "No tuvo ningún tipo de estudio",
                    ],
                    [
                        "field" => "a3s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 1,
                        "label" => "Sólo estudios primarios",
                    ],
                    [
                        "field" => "a4s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "Sólo estudios secundarios",
                    ],
                    [
                        "field" => "a5s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "Estudios técnicos",
                    ],
                    [
                        "field" => "a6s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "Estudios tecnológicos",
                    ],
                    [
                        "field" => "a7s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "Estudios profesionales",
                    ],
                    [
                        "field" => "a8s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "No sabe",
                    ],
                    [
                        "field" => "a9s6",
                        "type" => "checkbox",
                        "class" => "step_6",
                        "data" => 0,
                        "label" => "No responde",
                    ],
                ],
            ],
            "step_7" => [//Nivel de escolaridad de mi padre
                "id" => "step_7",
                "title" => "Nivel de escolaridad de mi padre",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 1,
                        "label" => "No la conocí",
                    ],
                    [
                        "field" => "a2s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 1,
                        "label" => "No tuvo ningún tipo de estudio",
                    ],
                    [
                        "field" => "a3s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 1,
                        "label" => "Sólo estudios primarios",
                    ],
                    [
                        "field" => "a4s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "Sólo estudios secundarios",
                    ],
                    [
                        "field" => "a5s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "Estudios técnicos",
                    ],
                    [
                        "field" => "a6s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "Estudios tecnológicos",
                    ],
                    [
                        "field" => "a7s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "Estudios profesionales",
                    ],
                    [
                        "field" => "a8s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "No sabe",
                    ],
                    [
                        "field" => "a9s7",
                        "type" => "checkbox",
                        "class" => "step_7",
                        "data" => 0,
                        "label" => "No responde",
                    ],
                ],
            ],
            "step_8" => [//¿Cuál es el nivel de ingresos familiares?
                "id" => "step_8",
                "title" => "¿Cuál es el nivel de ingresos familiares? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>Se entiende como salario mínimo el valor que por ley las empresas pagan a sus trabajadores y está en $1'117.172 pesos  (salario básico $1.000.000+ auxilio trasporte $117.172)</p>",
                "fields" => [
                    [
                        "field" => "a1s25",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 1,
                        "label" => "Menos de $1'117.172 mensuales",
                    ],
                    [
                        "field" => "a2s25",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 0,
                        "label" => "Más de $1'117.172 mensuales",
                    ],
                    [
                        "field" => "a3s25",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 0,
                        "label" => "No sabe",
                    ],
                    [
                        "field" => "a4s25",
                        "type" => "checkbox",
                        "class" => "step_8",
                        "data" => 0,
                        "label" => "No responde",
                    ],
                ],
            ],
            "step_9" => [//¿Cuál es tu grado educativo alcanzado?
                "id" => "step_9",
                "title" => "¿Cuál es tu grado educativo alcanzado?  ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 1,
                        "label" => "0°",
                    ],
                    [
                        "field" => "a2s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "1°",
                    ],
                    [
                        "field" => "a3s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "2°",
                    ],
                    [
                        "field" => "a4s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "3°",
                    ],
                    [
                        "field" => "a5s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "4°",
                    ],
                    [
                        "field" => "a6s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "5°",
                    ],
                    [
                        "field" => "a7s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "6°",
                    ],
                    [
                        "field" => "a8s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "7°",
                    ],
                    [
                        "field" => "a9s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "8°",
                    ],
                    [
                        "field" => "a10s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "9°",
                    ],
                    [
                        "field" => "a11s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "10°",
                    ],
                    [
                        "field" => "a12s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "11°",
                    ],
                    [
                        "field" => "a13s9",
                        "type" => "checkbox",
                        "class" => "step_9",
                        "data" => 0,
                        "label" => "12°",
                    ],
                ],
            ],
            "step_10" => [//¿Me siento aceptado(a) por mis compañeros(as) de clase o amigos(as)?
                "id" => "step_10",
                "title" => "¿Me siento aceptado(a) por mis compañeros(as) de clase o amigos(as)?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s10",
                        "type" => "checkbox",
                        "class" => "step_10",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s10",
                        "type" => "checkbox",
                        "class" => "step_10",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_11" => [//¿En los últimos tres meses has tenido relaciones sexuales con más de una persona?
                "id" => "step_11",
                "title" => "¿En los últimos tres meses has tenido relaciones sexuales con más de una persona? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s11",
                        "type" => "checkbox",
                        "class" => "step_11",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s11",
                        "type" => "checkbox",
                        "class" => "step_11",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_12" => [//¿Al  momento de  tener relaciones sexuales, utilizas preservativo?
                "id" => "step_12",
                "title" => "¿Al  momento de  tener relaciones sexuales, utilizas preservativo? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un Preservativo ?</p>
                <p>Más conocido como condón, es una funda  de látex (u otros materiales sintéticos) que se coloca en el pene del hombre para evitar el paso del semen hacia la mujer, evitando infecciones y embarazos. </p>
                <p>Tambien existen preservativos femenimos que funcionan de manera similar. </p>",
                "fields" => [
                    [
                        "field" => "a1s12",
                        "type" => "checkbox",
                        "class" => "step_12",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s12",
                        "type" => "checkbox",
                        "class" => "step_12",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_13" => [//¿Actualmente utilizas algún método anticonceptivo para prevenir embarazos?
                "id" => "step_13",
                "title" => "¿Actualmente utilizas algún método anticonceptivo para prevenir embarazos?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un método anticonceptivo ?</p><p>Son sustancias, objetos o procedimientos que evitan que la mujer quede embarazada. Por ejemplo; condón, las pastillas , inyecciones, parche, implante subdérmico condón (Masculino y femenino) , entre otros. </p>",
                "fields" => [
                    [
                        "field" => "a1s13",
                        "type" => "checkbox",
                        "class" => "step_13",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s13",
                        "type" => "checkbox",
                        "class" => "step_13",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_14" => [//¿Alguna  vez has  tenido relaciones sexuales  bajo los  efectos  del alcohol  u  otra droga?
                "id" => "step_14",
                "title" => "¿Alguna  vez has  tenido relaciones sexuales  bajo los  efectos  del alcohol  u  otra droga? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s14",
                        "type" => "checkbox",
                        "class" => "step_14",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s14",
                        "type" => "checkbox",
                        "class" => "step_14",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_15" => [//¿Alguna vez , tus relaciones sexuales han sido con personas mayores a 28 años?
                "id" => "step_15",
                "title" => "¿Alguna vez, tus relaciones sexuales han sido con personas mayores a 28 años?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s15",
                        "type" => "checkbox",
                        "class" => "step_15",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_16" => [//¿La relación establecida con tus madre, padre o cuidador te permite hablar de sexualidad?
                "id" => "step_16",
                "title" => "¿La relación establecida con tus madre, padre o cuidador te permite hablar de sexualidad?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s16",
                        "type" => "checkbox",
                        "class" => "step_16",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s16",
                        "type" => "checkbox",
                        "class" => "step_16",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_17" => [//¿Has  recibido información relacionada  con métodos de anticoncepción a través de amigos, padres de familia, docentes  u otras personas?
                "id" => "step_17",
                "title" => "¿Has  recibido información relacionada  con métodos de anticoncepción a través de amigos, padres de familia, docentes  u otras personas? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es un método anticonceptivo ?</p><p>Son sustancias, objetos o procedimientos que evitan que la mujer quede embarazada. Por ejemplo; condón, las pastillas , inyecciones, parche, implante subdérmico condón (Masculino y femenino) , entre otros. </p>",
                "fields" => [
                    [
                        "field" => "a1s17",
                        "type" => "checkbox",
                        "class" => "step_17",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s17",
                        "type" => "checkbox",
                        "class" => "step_17",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_18" => [//¿Tu  mamá  fue madre antes de los 19 años?
                "id" => "step_18",
                "title" => "¿Tu  mamá  fue madre antes de los 19 años? ",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s18",
                        "type" => "checkbox",
                        "class" => "step_18",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s18",
                        "type" => "checkbox",
                        "class" => "step_18",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_19" => [//¿Tu madre es cabeza de Familia y dependes economicamente de ella?
                "id" => "step_19",
                "title" => "¿Tu madre es cabeza de Familia y dependes economicamente de ella?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s19",
                        "type" => "checkbox",
                        "class" => "step_19",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s19",
                        "type" => "checkbox",
                        "class" => "step_19",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_20" => [//¿Alguna vez , has tenido relaciones sexuales bajo presión o en contra de tu voluntad?
                "id" => "step_20",
                "title" => "¿Alguna vez , has tenido relaciones sexuales bajo presión o en contra de tu voluntad?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s20",
                        "type" => "checkbox",
                        "class" => "step_20",
                        "data" => 1,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s20",
                        "type" => "checkbox",
                        "class" => "step_20",
                        "data" => 0,
                        "label" => "No",
                    ],
                ],
            ],
            "step_21" => [//¿Actualmente participas de alguna actividad deportiva, artística, cultural, grupo juvenil entre otras?
                "id" => "step_21",
                "title" => "¿Actualmente participas de alguna actividad deportiva, artística, cultural, grupo juvenil entre otras?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s21",
                        "type" => "checkbox",
                        "class" => "step_21",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s21",
                        "type" => "checkbox",
                        "class" => "step_21",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_22" => [//¿Actualmente trabajas para generar ingresos a la familia?
                "id" => "step_22",
                "title" => "¿Actualmente trabajas para generar ingresos a la familia?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 0,
                        "label" => "Si",
                    ],
                    [
                        "field" => "a2s22",
                        "type" => "checkbox",
                        "class" => "step_22",
                        "data" => 1,
                        "label" => "No",
                    ],
                ],
            ],
            "step_23" => [//¿Cuánto es tu sueldo actual?
                "id" => "step_23",
                "title" => "¿Cuánto es tu sueldo actual?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>Se entiende como salario mínimo el valor que por ley las empresas pagan a sus trabajadores y está en $1'117.172 pesos  (salario básico $1.000.000+ auxilio trasporte $117.172)</p>",
                "fields" => [
                    [
                        "field" => "a1s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 1,
                        "label" => "Menos de $1'117.172 mensuales",
                    ],
                    [
                        "field" => "a2s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "Más de $1'117.172 mensuales",
                    ],
                    [
                        "field" => "a3s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "No sabe",
                    ],
                    [
                        "field" => "a4s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "No responde",
                    ],
                    [
                        "field" => "a5s23",
                        "type" => "checkbox",
                        "class" => "step_23",
                        "data" => 0,
                        "label" => "No aplica"
                    ]
                ],
            ],
            "step_24" => [//Estrato socieconomico
                "id" => "step_24",
                "title" => "Estrato socieconómico",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "description" => "<p>¿ Qué es estrato socioeconómico ?</p><p>Es la forma en la que un pais clasifica las condiciones de la vivienda en la que habita un grupo de personas.
                Generalemnte,  Estrato 1: Bajo-Bajo  ,    Estrato 2: Bajo , Estrato 3: Medio-Bajo ,  Estrato 4: Medio , Estrato 5: Medio-Alto ,Estrato 6: Alto.</p>
                <p>Nota: Si no lo conoces preguntale al profesional a cargo</p>",
                "fields" => [
                    [
                        "field" => "a1s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 1,
                        "label" => "1",
                    ],
                    [
                        "field" => "a2s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 1,
                        "label" => "2",
                    ],
                    [
                        "field" => "a3s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 1,
                        "label" => "3",
                    ],
                    [
                        "field" => "a4s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 0,
                        "label" => "4",
                    ],
                    [
                        "field" => "a5s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 0,
                        "label" => "5",
                    ],
                    [
                        "field" => "a6s24",
                        "type" => "checkbox",
                        "class" => "step_24",
                        "data" => 0,
                        "label" => "6",
                    ]
                ],
            ],
            "step_25" => [//¿Con cual de los siguientes grupos étnicos te identificas?
                "id" => "step_25",
                "title" => "¿Con cual de los siguientes grupos étnicos te identificas?",
                "show" => "d-none",
                "btnEnd" => false,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 0,
                        "label" => "No aplica",
                    ],
                    [
                        "field" => "a2s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Indígena",
                    ],
                    [
                        "field" => "a3s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Negritudes",
                    ],
                    [
                        "field" => "a4s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Rom",
                    ],
                    [
                        "field" => "a5s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Otras etnias",
                    ],
                    [
                        "field" => "a6s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Raizales",
                    ],
                    [
                        "field" => "a7s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Afrodescendientes",
                    ],
                    [
                        "field" => "a8s25",
                        "type" => "checkbox",
                        "class" => "step_25",
                        "data" => 1,
                        "label" => "Palanquero",
                    ],
                ],
            ],
            "step_26" => [//Edad tu primera menstruación
                "id" => "step_26",
                "title" => "Edad tu primera menstruación",
                "show" => "d-none",
                "btnEnd" => true,
                "changeSteps" => true,
                "fields" => [
                    [
                        "field" => "a1s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 1,
                        "label" => "11 a 14 años",
                    ],
                    [
                        "field" => "a2s26",
                        "type" => "checkbox",
                        "class" => "step_26",
                        "data" => 0,
                        "label" => "15 a 19 años",
                    ],
                ],
            ] */
        ];

        $responses = [
            [//riesgo alto que se muestra en el front
                "genero" => true,
                "titulo" => ["<h1>Camilo</h1>","<h1>Camila</h1>"], //riesgo alto
                "image" => ["/images/camilo_alto.png", "/images/camila_alto.png"],
                "texto" => "<p>Tu vida viene desarrollándose en un contexto económico, social y cultural que te expone a un alto riesgo de un embarazo adolescente, pero ¡¡¡ANIMO!!!, Tu eres muy inteligente y  sabes  que  con  acceso  a  métodos  de  anticoncepción  y  un  proyecto  de  vida  claro,  tú DECIDES tu futuro, a continuación, te invitamos a conocer el directorio de oferta para la Prevención  de  Embarazo  Adolescente  y  a  conectarte  con  la  línea  amiga  en  Salud 3007231123  </p>
                <p>Es  importante  seguir  estas  recomendaciones  y  empoderarse  de  tu  futuro,  pues  Los padres y Las madres en la adolescencia reciben menos salario y tienen mayor tasa de desempleo, además están en alto riesgo de abandonar o postergar sus estudios, y muy pocos logran culminar una formación universitaria.  </p>
                <p>Si  eres  menor  de  14  años  recuerda  que  un  embarazo  a  tan  temprana  edad  es considerado por ley delito, por ello tienen unos derechos especiales que puedes consultar con un profesional en salud.</p>",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
            [//riesgo medio
                "genero" => true,
                "titulo" => ["<h1>Andres</h1>","<h1>Andrea</h1>"], //riesgo medio
                "image" => ["/images/andres_medio.png", "/images/andrea_medio.png"],
                "texto" => "<p>Tu vida viene desarrollándose en un contexto económico, social y cultural que te expone a un riesgo medio de un embarazo adolescente, pero ¡¡¡ANIMO!!!Tu eres muy inteligente y  sabes  que  con  acceso  a  métodos  de  anticoncepción  y  un  proyecto  de  vida  claro,  tú DECIDES tu futuro, a continuación, te invitamos a conocer el directorio de Prevención de Embarazo Adolescente y a conectarte con la línea amiga en Salud 3007231123 </p>
                <p>Es  importante  seguir  estas  recomendaciones  y  empoderarse  de  tu  futuro,  pues  Los padres y Las madres en la adolescencia reciben menos salario y tienen mayor tasa de desempleo, además están en riesgo de abandonar o postergar sus estudios, y muy pocos logran culminar una formación universitaria.  </p>
                ",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
            [//riesgo bajo
                "genero" => true,
                "titulo" => ["<h1>Diego</h1>","<h1>Erika</h1>"], //riesgo bajo
                "image" => ["/images/diego_bajo.png", "/images/erika_bajo.png"],
                "texto" => "<p>Al estar en un riesgo bajo de un embarazo adolescente tienes una gran posibilidad de terminar una carrera universitaria, un postgrado, devengar un buen salario, sin embargo, no te confíes , siempre es necesario consultar un profesional de la salud y tener metas y sueños  claros,  te  invitamos  a  conocer  el  directorio  de  oferta  para  la  Prevención  de Embarazo Adolescente y a conectarte con la línea amiga en Salud 3007231123. </p>
                ",
                "recordatorio" => "<h1>Y RECUERDA NO CREAS EN MITOS</h1>",
                "politicas" => [
                    "La mujer nunca queda embarazada en la primera relación sexual. ",
                    "A las mujeres que han tenido relaciones sexuales se les arquean las piernas. ",
                    "El lavado vaginal después de la relación sexual es un método eficaz para evitar el embarazo.",
                    "Durante la menstruación la mujer no debe practicar deportes, lavarse o cortarse el cabello, cargar bebés, cortar las plantas, entre otras actividades. ",
                    "Si la mujer no sangra en su primera relación sexual, quiere decir que no es virgen.",
                    "El VIH-SIDA se contagia sólo si se tiene relaciones sexuales con homosexuales o prostitutas. ",
                    "Las vaginas de las mujeres huelen a pescado. ",
                    "Si  un  hombre  se  masturba  demasiado,  tarde  o  temprano  se  le  acabarán  los espermatozoides",
                    "El lugar más seguro para guardar el condón es la billetera.",
                    "EL VIH puede pasar por los condones porque el condón se rompe con facilidad.",
                    "Días antes y días después del periodo la mujer no queda embarazada .",
                    "Retirar el pene de la vagina antes de eyacular es una forma efectiva de  prevenir el embarazo. ",
                    "La masturbación es practicada casi exclusivamente por los hombres  .",
                    "La vasectomía causa impotencia o disfunción eréctil en el hombre. ",
                    "Los que calzan grande lo tienen grande .",
                ]
            ],
        ];

        $instituciones = [
            "INSTITUCION EDUCATIVA FE Y ALEGRIA JOSE MARIA VELAZ",
            "INSTITUCION EDUCATIVA BARRIO SANTA CRUZ",
            "INSTITUCION EDUCATIVA CENTRO FORMATIVO DE ANTIOQUIA -CEFA",
            "INSTITUCION EDUCATIVA JOSE MARIA BERNAL",
            "INSTITUCION EDUCATIVA PRESBITERO CAMILO TORRES RESTREPO",
            "INSTITUCION EDUCATIVA SAN AGUSTIN",
            "INSTITUCION EDUCATIVA HECTOR ABAD GOMEZ",
        ];

        $documentos = [
            "Cédula de ciudadanía",
            "Tarjeta de identidad",
            "Pasaporte",
            "Permiso Especial de permanencia",
            "Documento extranjero",
        ];

        return view('welcome', [
            'steps' => $steps,
            'finalForm' => $finalForm,
            'responses' => $responses,
            'instituciones' => $instituciones,
            'documentos' => $documentos,
        ]);
    }
}
